ShakeCharity/ShakeSharityApp/force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/ShakeCharity__c.object-meta.xml
<CustomObject>
    <label>ShakeCharity</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>ShakeCharity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ShakeCharity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ShakeCharity</relationshipLabel>
    <relationshipName>ShakeCharity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/classes/GetCharityCtrl.cls
public class GetCharityCtrl {
	@auraEnabled
    Public  static string getAccount(Id sAccountId){
        string sSuccess = 'Success';
        List<ShakeCharity__c> lstShakeCharity = [SELECT Id, Account__c FROM ShakeCharity__c WHERE Account__c=:sAccountId];
        if(lstShakeCharity != null && lstShakeCharity.size()>0){
        	sSuccess = 'RecordExist' ;  
        }
        else {
        	List<Account> lstAccount = [SELECT Id, Name, EIN__c FROM Account WHERE Id = :sAccountId];
            if(lstAccount.size()>0){
                for(Account oAcc : lstAccount){
                    if(oAcc.EIN__c != null){
                        AWSCallout.callAwsgateway(oAcc.EIN__c);  
                        sSuccess = 'Success';
                    }
                    else {
                         sSuccess = 'Failure';
                    } 
                } 
            }    
        }
    	return sSuccess;    
    }
    
    @auraEnabled
    Public  static string getCharityData(string sEIN){
        string sSuccess = 'Success';
        AWSCallout.callAwsgateway(sEIN);
    	return sSuccess;
    }
}