ShakeCharity/ShakeSharityApp/force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>An Account representing an organization</description>
    <label>Organization</label>
</RecordType>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/ShakeCharity__c.object-meta.xml
<CustomObject>
    <label>ShakeCharity</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>ShakeCharity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ShakeCharity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ShakeCharity</relationshipLabel>
    <relationshipName>ShakeCharity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/ACCT_PD__c.field-meta.xml
<CustomField>
    <fullName>ACCT_PD__c</fullName>
    <inlineHelpText>ACCOUNTING PERIOD
This designates the accounting period or fiscal year ending date (Jan - Dec) of the organization (MM)</inlineHelpText>
    <label>ACCT PD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <inlineHelpText>An organization formerly listed up to three activity codes on application Forms 1023 and 1024. These are codes which
reflect an organization&apos;s purposes, activities, operations, or type.</inlineHelpText>
    <label>Activity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <inlineHelpText>The Affiliation Code defines the organizational grouping.</inlineHelpText>
    <label>Affiliation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Asset_AMT__c.field-meta.xml
<CustomField>
    <fullName>Asset_AMT__c</fullName>
    <inlineHelpText>Asset Amount is an amount from the most recent Form 990 series return filed by the organization. Asset Amount is the Book Value Total Assets End of Year - PART X Balance Sheet Line 16 Col. (B) shown on the Form 990.</inlineHelpText>
    <label>Asset Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Billing_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Billing_Pincode__c</fullName>
    <label>Billing Pincode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Deductablity_Status_Desacription__c.field-meta.xml
<CustomField>
    <fullName>Deductablity_Status_Desacription__c</fullName>
    <inlineHelpText>Deductibility Code signifies whether contributions made to an organization are deductible.
Code Description
1 - Contributions are deductible.
2 - Contributions are not deductible.
4 - Contributions are deductible by treaty (foreign organizations).</inlineHelpText>
    <label>Deductablity Code</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Filing_REQ_CD__c.field-meta.xml
<CustomField>
    <fullName>Filing_REQ_CD__c</fullName>
    <inlineHelpText>This indicates the primary return(s) the organization is required to file.</inlineHelpText>
    <label>Filing REQ CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Foundation__c.field-meta.xml
<CustomField>
    <fullName>Foundation__c</fullName>
    <label>Foundation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Foundation_Code__c.field-meta.xml
<CustomField>
    <fullName>Foundation_Code__c</fullName>
    <inlineHelpText>This defines the type of organization as follows:
Code Description
1 Corporation
2 Trust
3 Co-operative
4 Partnership
5 Association</inlineHelpText>
    <label>Organization Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Foundation_Status__c.field-meta.xml
<CustomField>
    <fullName>Foundation_Status__c</fullName>
    <label>Organization Status</label>
    <type>TextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>This is a four-digit internal number assigned to central/parent organizations holding group exemption letters.</inlineHelpText>
    <label>Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/In_Care_of__c.field-meta.xml
<CustomField>
    <fullName>In_Care_of__c</fullName>
    <inlineHelpText>In Care of Name</inlineHelpText>
    <label>In Care of</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Income_AMT__c.field-meta.xml
<CustomField>
    <fullName>Income_AMT__c</fullName>
    <inlineHelpText>Income Amount is a computer generated amount from the most recent Form 990 series return filed by the organization.
Income Amount is computer generated using PART I, Total Revenue Line 12 and adding &quot;back in&quot; the expense items.</inlineHelpText>
    <label>Income AMT</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Income_CD__c.field-meta.xml
<CustomField>
    <fullName>Income_CD__c</fullName>
    <inlineHelpText>Income Codes relate to the amount of income shown on the most recent Form 990 series return filed by the organization.</inlineHelpText>
    <label>Income CD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/IRS_Org_Name__c.field-meta.xml
<CustomField>
    <fullName>IRS_Org_Name__c</fullName>
    <label>IRS Organization Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/NTEE_Code__c.field-meta.xml
<CustomField>
    <fullName>NTEE_Code__c</fullName>
    <inlineHelpText>The National Taxonomy of Exempt Entities (NTEE) Code is a four digit code used to classify an exempt organization in
terms of its primary exempt activity.</inlineHelpText>
    <label>NTEE Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Organaization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organaization_Id__c</fullName>
    <label>Organization Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/PF_Filing_REQ_CD__c.field-meta.xml
<CustomField>
    <fullName>PF_Filing_REQ_CD__c</fullName>
    <inlineHelpText>PF FILING REQUIREMENT CODE
Code Form Numbers
1 990-PF return
0 No 990-PF return</inlineHelpText>
    <label>PF Filing REQ CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Ruling_Date__c.field-meta.xml
<CustomField>
    <fullName>Ruling_Date__c</fullName>
    <inlineHelpText>This is the month and year (YYYYMM) on a ruling or determination letter recognizing the organization&apos;s exempt status.</inlineHelpText>
    <label>Ruling Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The EO Status Code defines the type of exemption held by the organization. The following is a list of EO status codes and
their definitions:
 Code Description
01 Unconditional Exemption
02 Conditional Exemption
12 Trust described i</inlineHelpText>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Subsection_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsection_Code__c</fullName>
    <inlineHelpText>Subsection Codes are the codes shown under section 501(c) of the Internal Revenue Code of 1986, which define the category under which an organization may be exempt.</inlineHelpText>
    <label>Subsection Code</label>
    <type>TextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Last filed taxes on:</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <inlineHelpText>Amount from Form 990, Part 1, Line 12, or Part 1, Line 9, of Form 990EZ</inlineHelpText>
    <label>Revenue Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/classes/SearchCharitydata.cls
global class SearchCharitydata {
    @AuraEnabled
    public static List<wrapperClass> callAwsgateway(string EIN) {
        wrapperClass returnwrapperClass = new  wrapperClass (); 
        List<wrapperClass> lstWrapper = new List<wrapperClass>(); 
        Http http = new Http();
         List<Account> UpdateAcc = new List<Account>();
        system.debug('EIN====='+EIN );
        EIN = EIN.replace('-', '');
        string sEndPoint = 'https://agbg6e5ci7.execute-api.us-east-2.amazonaws.com/CharityBeta/charitydata/'+EIN;
        HttpRequest request = new HttpRequest();

        //Please set the endpoint of API gateway which we are going to create in later section
        request.setEndpoint(sEndPoint);
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');

        // Set the body as a JSON object
        HttpResponse response = http.send(request);
        System.debug('response==='+response.getBody());
        String body;
        JSONParser parser = JSON.createParser(response.getBody());
        system.debug(parser );
        system.debug(parser.nextToken());
        system.debug(parser.getCurrentToken());

        if(parser.getCurrentToken() == JSONToken.START_OBJECT) {
            parser.nextValue();
            system.debug(parser.getCurrentName());
            parser.nextValue();
            system.debug(parser.getCurrentName());
            if(parser.getCurrentName() == 'SORT_NAME') {
                returnwrapperClass.sSortName = parser.getText();
                parser.nextValue();
            } 
            if (parser.getCurrentName() == 'INCOME_CD') {
                parser.nextValue();
            } 

            if (parser.getCurrentName() == 'CITY') {
                system.debug(parser.getText() );
                returnwrapperClass.sCity=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ASSET_AMT') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'AFFILIATION') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'EIN') {
                system.debug(parser.getText() );
                returnwrapperClass.sEIN=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'STREET') {
                system.debug(parser.getText() );
                returnwrapperClass.sStreet=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'CLASSIFICATION') {
                system.debug(parser.getText() );
                parser.nextValue();
            } 

            if (parser.getCurrentName() == 'ORGANIZATION') {
                system.debug(parser.getText() );
                parser.nextValue();
            } 

            if (parser.getCurrentName() == 'REVENUE_AMT') {
                system.debug(parser.getText() );
                parser.nextValue();
            } 

            if (parser.getCurrentName() == 'SUBSECTION') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ICO') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'INCOME_AMT') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ASSET_CD') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'TAX_PERIOD') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'RULING') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ZIP') {
                system.debug(parser.getText() );
                returnwrapperClass.sZip=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'DEDUCTIBILITY') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ACTIVITY') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'FILING_REQ_CD') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'OrgNAME') {
                system.debug(parser.getText() );
                returnwrapperClass.sName=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'FOUNDATION') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'NTEE_CD') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'STATUS') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'PF_FILING_REQ_CD') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ACCT_PD') {
                system.debug(parser.getText() );
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'STATE') {
                system.debug(parser.getText() );
                returnwrapperClass.sState=parser.getText() ;
                parser.nextValue();
            }
        }  
        List<ShakeCharity__c> lstShakeCharity = [SELECT Id, Name FROM ShakeCharity__c WHERE EIN__c=:EIN LIMIT 1];
        if(lstShakeCharity.size()>0 && lstShakeCharity != null){ 
            returnwrapperClass.sExist = true;
            returnwrapperClass.sRecordID = lstShakeCharity[0].Id;
        }

        // Parse the JSON response
        if (response.getStatusCode() != 201) {
            System.debug('The status code returned was not expected: ' +
            response.getStatusCode() + ' ' + response.getStatus());

        }

        else {
            System.debug(response.getBody());

        }
        lstWrapper.add(returnwrapperClass);
        system.debug(lstWrapper.size());
        return lstWrapper;
    }
    
    @AuraEnabled
    public static List<wrapperClass> callAwsgatewayOrgSearch(string EIN) {
        map<string,Id> mapAcc = new map<string,Id>();
        EIN = EIN.replace('-', '');
        system.debug(EIN.length());
        List<ShakeCharity__c> lstShakeCharity = [SELECT Id, EIN__c FROM ShakeCharity__c WHERE EIN__c != null];
        if(lstShakeCharity != null && lstShakeCharity.size()>0){
            for(ShakeCharity__c oShakeCharity : lstShakeCharity){
                mapAcc.put(oShakeCharity.EIN__c,oShakeCharity.Id);
            }
        }
        system.debug(mapAcc);
        set<wrapperClass> lstWrapper = new set<wrapperClass>(); 
        Http http = new Http();
        HttpResponse response;
        List<ShakeCharity__c> updateShakeCharity = new List<ShakeCharity__c>();
        if(EIN.isNumeric()){
          	system.debug('EIN====='+EIN );
            string sEndPoint = 'https://agbg6e5ci7.execute-api.us-east-2.amazonaws.com/CharityBeta/charitydata/'+EIN;
            HttpRequest request = new HttpRequest();
    
            //Please set the endpoint of API gateway which we are going to create in later section
            request.setEndpoint(sEndPoint);
            request.setMethod('GET');
            request.setHeader('Content-Type', 'application/json');
    
            // Set the body as a JSON object
            response = http.send(request);
            if(response != null){
            	System.debug('response123==='+response.getBody());    
            }
            else{
            	System.debug('response==='+response.getBody());    
            }
            
            String body;
            JSONParser parser = JSON.createParser(response.getBody());
            
            Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(response.getBody().replaceAll('\n','').replaceAll('\r',''));
            system.debug(results);
            Map<String, Object> data = (Map<String, Object>)results.get('Item');
            system.debug(data.keySet());
            for(String key : data.keySet()){
                System.debug('### lines.get(key) : ' + data.get('SORT_NAME'));
                System.debug('### >>> ' + data.get(key));
                wrapperClass returnwrapperClass = new  wrapperClass ();
                  returnwrapperClass.sSortName  = string.valueof(data.get('OrgNAME'));
                    returnwrapperClass.sCity  = string.valueof(data.get('CITY'));
                    returnwrapperClass.sEIN  = string.valueof(data.get('EIN'));
                    returnwrapperClass.sZip  = string.valueof(data.get('ZIP'));
                    returnwrapperClass.sSTATE  = string.valueof(data.get('STATE'));
                    returnwrapperClass.sName  = string.valueof(data.get('OrgNAME'));
                    returnwrapperClass.sStreet  = string.valueof(data.get('STREET'));
                    Object oEIN = mapAcc.get(string.valueof(data.get('EIN')));
                    if(oEIN != null){
                        returnwrapperClass.sExist = true;
                        returnwrapperClass.sIsSalesforce = true;
                        returnwrapperClass.sRecordID = mapAcc.get(string.valueof(data.get('EIN')));
                    }
                    lstWrapper.add(returnwrapperClass);
                    System.debug(lstWrapper);
                break;
            }  
        }

        else{
          system.debug('EIN====='+EIN );
            String sEIN= '%'+EIN+'%';
            system.debug(sEIN);
            List<Account> lstAccount = [SELECT id, EIN__c, Name, BillingCity, BillingState, BillingStreet, BillingPostalCode  FROM Account WHERE Name like: sEIN];
            if(lstAccount != null && lstAccount.size()>0){
                for(Account oAcc : lstAccount){
                    if(!oAcc.Name.contains('Household')){
                        wrapperClass returnwrapperClass = new  wrapperClass ();
                        returnwrapperClass.sSortName  = oAcc.Name;
                        returnwrapperClass.sEIN  = oAcc.EIN__c;
                        returnwrapperClass.sName  = oAcc.Name;
                        returnwrapperClass.sCity  = oAcc.BillingCity;
                        returnwrapperClass.sSTATE  = oAcc.BillingState;
                        returnwrapperClass.sZip  =  oAcc.BillingPostalCode;
                        returnwrapperClass.sStreet  =  oAcc.BillingStreet;
                        returnwrapperClass.sExist = true;
                        returnwrapperClass.sIsSalesforce = true;
                        returnwrapperClass.sRecordID = oAcc.Id;
                        lstWrapper.add(returnwrapperClass);    
                    }
                }
            }
            EIN = EIN.toUppercase();
            string sEndPoint = 'https://3k0fpzhw53.execute-api.us-east-2.amazonaws.com/Pro/charitydata/'+EIN;
            HttpRequest request = new HttpRequest();
    
            //Please set the endpoint of API gateway which we are going to create in later section
            request.setEndpoint(sEndPoint);
            request.setMethod('GET');
            request.setHeader('Content-Type', 'application/json');
    
            // Set the body as a JSON object
            response = http.send(request);
            System.debug('response==='+response.getBody());
            //String body;
            JSONParser parser = JSON.createParser(response.getBody());
            String body = response.getBody();
            system.debug(body);
            Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            List<Object> lstCustomers = (List<Object>)results.get('Items');
            Object[] aryCustomers = (Object[]) results.get('Items');
            system.debug('results===='+results);
            system.debug('lstCustomers===='+lstCustomers);
            system.debug('aryCustomers===='+aryCustomers);
            for (Object customer : lstCustomers) {
                Map<String, Object> customerAttributes = (Map<String, Object>)customer;
                wrapperClass returnwrapperClass = new  wrapperClass ();
                    // handle response
                    returnwrapperClass.sSortName  = string.valueof(customerAttributes.get('OrgNAME'));
                    returnwrapperClass.sCity  = string.valueof(customerAttributes.get('CITY'));
                    returnwrapperClass.sEIN  = string.valueof(customerAttributes.get('EIN'));
                    returnwrapperClass.sZip  = string.valueof(customerAttributes.get('ZIP'));
                    returnwrapperClass.sSTATE  = string.valueof(customerAttributes.get('STATE'));
                    returnwrapperClass.sName  = string.valueof(customerAttributes.get('OrgNAME'));
                    returnwrapperClass.sStreet  = string.valueof(customerAttributes.get('STREET'));
                    Object oEIN = mapAcc.get(string.valueof(customerAttributes.get('EIN')));
                    if(oEIN != null){
                        returnwrapperClass.sExist = true;
                        returnwrapperClass.sIsSalesforce = true;
                        returnwrapperClass.sRecordID = mapAcc.get(string.valueof(customerAttributes.get('EIN')));
                    }
                    lstWrapper.add(returnwrapperClass);
                    System.debug(lstWrapper);
                } 
            }
        
        // Parse the JSON response
        if (response.getStatusCode() != 201) {
            System.debug('The status code returned was not expected: ' +
            response.getStatusCode() + ' ' + response.getStatus());

        } else {
            System.debug(response.getBody());

        }
        List<wrapperClass> listwrap = new List<wrapperClass>(lstWrapper);
        return listwrap;
    }
    
    // wrapper or Inner class with @AuraEnabled {get;set;} properties*    
    public class wrapperClass{
        @AuraEnabled public String sSortName {get;set;}
        @AuraEnabled public String sName {get;set;}
        @AuraEnabled public String sCity {get;set;}
        @AuraEnabled public String sState {get;set;}
        @AuraEnabled public String sEIN {get;set;}
        @AuraEnabled public String sStreet {get;set;}
        @AuraEnabled public String sZip {get;set;}
        @AuraEnabled public boolean sExist {get;set;}
        @AuraEnabled public string sRecordID {get;set;}
        @AuraEnabled public string sResponse {get;set;}
        @AuraEnabled public boolean sIsSalesforce {get;set;}
        @AuraEnabled public string sCharityRecord {get;set;}
        public wrapperClass(){  
        }
    }
  
  public class OrgData{
        @AuraEnabled public String sSortName1 {get;set;}
        @AuraEnabled public String sName1 {get;set;}
        @AuraEnabled public String sCity1 {get;set;}
        @AuraEnabled public String sState1 {get;set;}
        @AuraEnabled public String sEIN1 {get;set;}
        @AuraEnabled public String sStreet1 {get;set;}
        @AuraEnabled public String sZip1 {get;set;}
        public OrgData(String sSortName1, String sName1, String sCity1, String sState1, String sEIN1,  String sStreet1, String sZip1){
            this.sSortName1 = sSortName1;
            this.sName1 = sName1;
            this.sCity1 = sCity1;
            this.sState1 = sState1;
            this.sEIN1 = sEIN1;
            this.sStreet1 = sStreet1;
            this.sZip1 = sZip1;   
        }
    }
    
    @AuraEnabled
    public static List<ShakeCharity__c> createRecord(string EIN) {
        string sAccountId;
        Http http = new Http();
        List<ShakeCharity__c> createShakeCharity = new List<ShakeCharity__c>();
        system.debug('EIN====='+EIN );
        EIN = EIN.replace('-', '');
        string sEndPoint = 'https://agbg6e5ci7.execute-api.us-east-2.amazonaws.com/CharityBeta/charitydata/'+EIN;
        HttpRequest request = new HttpRequest();

        //Please set the endpoint of API gateway which we are going to create in later section
        request.setEndpoint(sEndPoint);
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');

        // Set the body as a JSON object
        HttpResponse response = http.send(request);
        System.debug('response==='+response.getBody());
        String body;
        JSONParser parser = JSON.createParser(response.getBody());
        system.debug(parser );
        system.debug(parser.nextToken());
        system.debug(parser.getCurrentToken());
        
        List<Account> oAccount = [SELECT Id FROM Account WHERE EIN__c =:EIN LIMIT 1];
        if(oAccount.size() >0){
        	sAccountId = oAccount[0].Id;     
        }
        Account newAcc = new Account();
        ShakeCharity__c oShakeCharity = new ShakeCharity__c();
        if(parser.getCurrentToken() == JSONToken.START_OBJECT) {
            parser.nextValue();
            system.debug(parser.getCurrentName());
            parser.nextValue();
            system.debug(parser.getCurrentName());
            if(parser.getCurrentName() == 'SORT_NAME') {
                system.debug(parser.getText() );
                parser.nextValue();
            } 

            if (parser.getCurrentName() == 'INCOME_CD') {
                system.debug(parser.getText() );
                oShakeCharity.Income_CD__c=parser.getText() ;
                parser.nextValue();
            } 

            if (parser.getCurrentName() == 'CITY') {
                system.debug(parser.getText() );
                oShakeCharity.Billing_City__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ASSET_AMT') {
                system.debug(parser.getText() );
                oShakeCharity.Asset_AMT__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'AFFILIATION') {
                system.debug(parser.getText() );
				oShakeCharity.Affiliation__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'EIN') {
                system.debug(parser.getText() );
                oShakeCharity.EIN__c=parser.getText() ;
                if(sAccountId == null){
                	newAcc.EIN__c=parser.getText();    
                }
                parser.nextValue();

            }
            
            if (parser.getCurrentName() == 'STREET') {
                system.debug(parser.getText() );
                oShakeCharity.Billing_Street__c=parser.getText() ;
                parser.nextValue();

            }
            
            if (parser.getCurrentName() == 'CLASSIFICATION') {
                system.debug(parser.getText() );
                oShakeCharity.Classification__c=parser.getText() ;
                parser.nextValue();

            } 
            
            if (parser.getCurrentName() == 'ORGANIZATION') {
                system.debug(parser.getText() );
                oShakeCharity.Organaization_Id__c=parser.getText() ;
                parser.nextValue();

            } 
            
            if (parser.getCurrentName() == 'REVENUE_AMT') {
                system.debug(parser.getText() );
                oShakeCharity.Total_Revenue__c=parser.getText() ;
                parser.nextValue();
            } 
            
            if (parser.getCurrentName() == 'SUBSECTION') {
                system.debug(parser.getText() );
                oShakeCharity.Subsection_Code__c=parser.getText() ;
                if(parser.getText() == '1'){
                    oShakeCharity.Foundation_Status__c='501(c)(1) ' + + ' Corporations Organized under Act of Congress (including Federal Credit Unions)';
                }
                if(parser.getText() == '2'){
                    oShakeCharity.Foundation_Status__c='501(c)(2) ' + + ' Title Holding Corporation for Exempt Organization';
                }
                if(parser.getText() == '3'){
                    oShakeCharity.Foundation_Status__c='501(c)(3) ' + + ' Religious, Educational, Charitable, Scientific, Literary, Testing for Public Safety, to Foster National or International Amateur Sports Competition, or Prevention of Cruelty to Children or Animals Organizations';
                }
                if(parser.getText() == '4'){
                    oShakeCharity.Foundation_Status__c='501(c)(4) ' + + ' Civic Leagues, Social Welfare Organizations, and Local Associations of Employees';
                }     
                if(parser.getText() == '5'){
                    oShakeCharity.Foundation_Status__c='501(c)(5) ' + + ' Labor, Agricultural, and Horticultural Organizations';
                }
                parser.nextValue();
            }
             
            if (parser.getCurrentName() == 'ICO') {
                system.debug(parser.getText() );
                string sContactPerson = parser.getText();
                oShakeCharity.In_Care_of__c=sContactPerson.replace('%','') ;
                parser.nextValue();
            }
             
            if (parser.getCurrentName() == 'INCOME_AMT') {
                system.debug(parser.getText() );
                oShakeCharity.Income_AMT__c=parser.getText() ;
                parser.nextValue();
            }
             
            if (parser.getCurrentName() == 'ASSET_CD') {
                system.debug(parser.getText() );
                //oShakeCharity.Income_AMT__c=parser.getText() ;
                parser.nextValue();
            }
             
            if (parser.getCurrentName() == 'TAX_PERIOD') {
                system.debug(parser.getText() );
                string sTaxYear = parser.getText();
                string sYear = ((String)sTaxYear).left(4);
                string sMonth = ((String)sTaxYear).right(2);
                oShakeCharity.Tax_Year__c=sMonth+'/'+sYear ;
                parser.nextValue();
            }
             
            if (parser.getCurrentName() == 'RULING') {
                system.debug(parser.getText() );
                string sRuleYear = parser.getText();
                string sYear = ((String)sRuleYear).left(4);
                string sMonth = ((String)sRuleYear).right(2);
                oShakeCharity.Ruling_Date__c=sMonth+'/'+sYear ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ZIP') {
                system.debug(parser.getText() );
                oShakeCharity.Billing_Pincode__c=parser.getText() ;
                parser.nextValue();
            }
            
            if (parser.getCurrentName() == 'DEDUCTIBILITY') {
                system.debug(parser.getText() );
                oShakeCharity.Deductablity_Status_Desacription__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ACTIVITY') {
                system.debug(parser.getText() );
                oShakeCharity.Activity__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'FILING_REQ_CD') {
                system.debug(parser.getText() );
                oShakeCharity.Filing_REQ_CD__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'OrgNAME') {
                system.debug(parser.getText() );
                oShakeCharity.IRS_Org_Name__c=parser.getText() ;
                if(sAccountId == null){
                	newAcc.Name=parser.getText();    
                }
                parser.nextValue(); 
            }

            if (parser.getCurrentName() == 'FOUNDATION') {
                system.debug(parser.getText() );
                //oShakeCharity.Foundation_Code__c=parser.getText() ;
                oShakeCharity.Foundation__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'NTEE_CD') {
                system.debug(parser.getText() );
                oShakeCharity.NTEE_Code__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'STATUS') {
                system.debug(parser.getText() );
                oShakeCharity.Status__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'PF_FILING_REQ_CD') {
                system.debug(parser.getText() );
                oShakeCharity.PF_Filing_REQ_CD__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'ACCT_PD') {
                system.debug(parser.getText() );
                oShakeCharity.ACCT_PD__c=parser.getText() ;
                parser.nextValue();
            }

            if (parser.getCurrentName() == 'STATE') {
                system.debug(parser.getText() );
                oShakeCharity.Billing_State__c=parser.getText() ;
                parser.nextValue();
            }
            
            if (parser.getCurrentName() == 'GROUP') {
                system.debug(parser.getText() );
                oShakeCharity.Group__c=parser.getText() ;
                parser.nextValue();
            }
			if(sAccountId == null){
                insert newAcc;
                sAccountId = newAcc.Id;
        	}
            oShakeCharity.Account__c=sAccountId;
            createShakeCharity.add(oShakeCharity);
        }
        if(createShakeCharity.size()>0){
            insert createShakeCharity;   
        }
        return createShakeCharity;
    }
}