ShakeCharity/ShakeSharityApp/force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>An Account representing an organization</description>
    <label>Organization</label>
</RecordType>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/ShakeCharity__c.object-meta.xml
<CustomObject>
    <label>ShakeCharity</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>ShakeCharity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ShakeCharity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ShakeCharity</relationshipLabel>
    <relationshipName>ShakeCharity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/ACCT_PD__c.field-meta.xml
<CustomField>
    <fullName>ACCT_PD__c</fullName>
    <inlineHelpText>ACCOUNTING PERIOD
This designates the accounting period or fiscal year ending date (Jan - Dec) of the organization (MM)</inlineHelpText>
    <label>ACCT PD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <inlineHelpText>An organization formerly listed up to three activity codes on application Forms 1023 and 1024. These are codes which
reflect an organization&apos;s purposes, activities, operations, or type.</inlineHelpText>
    <label>Activity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <inlineHelpText>The Affiliation Code defines the organizational grouping.</inlineHelpText>
    <label>Affiliation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Asset_AMT__c.field-meta.xml
<CustomField>
    <fullName>Asset_AMT__c</fullName>
    <inlineHelpText>Asset Amount is an amount from the most recent Form 990 series return filed by the organization. Asset Amount is the Book Value Total Assets End of Year - PART X Balance Sheet Line 16 Col. (B) shown on the Form 990.</inlineHelpText>
    <label>Asset Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Automatic_Revocation__c.field-meta.xml
<CustomField>
    <fullName>Automatic_Revocation__c</fullName>
    <label>Automatic Revocation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Billing_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Billing_Pincode__c</fullName>
    <label>Billing Pincode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Bridge_Number__c.field-meta.xml
<CustomField>
    <fullName>Bridge_Number__c</fullName>
    <label>Bridge Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Company_Mission__c.field-meta.xml
<CustomField>
    <fullName>Company_Mission__c</fullName>
    <label>Company Mission</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Deductablity_Status_Desacription__c.field-meta.xml
<CustomField>
    <fullName>Deductablity_Status_Desacription__c</fullName>
    <inlineHelpText>Deductibility Code signifies whether contributions made to an organization are deductible.
Code Description
1 - Contributions are deductible.
2 - Contributions are not deductible.
4 - Contributions are deductible by treaty (foreign organizations).</inlineHelpText>
    <label>Deductablity Code</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Filing_REQ_CD__c.field-meta.xml
<CustomField>
    <fullName>Filing_REQ_CD__c</fullName>
    <inlineHelpText>This indicates the primary return(s) the organization is required to file.</inlineHelpText>
    <label>Filing REQ CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <label>Form Type</label>
    <type>TextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Foundation__c.field-meta.xml
<CustomField>
    <fullName>Foundation__c</fullName>
    <label>Foundation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Foundation_Code__c.field-meta.xml
<CustomField>
    <fullName>Foundation_Code__c</fullName>
    <inlineHelpText>This defines the type of organization as follows:
Code Description
1 Corporation
2 Trust
3 Co-operative
4 Partnership
5 Association</inlineHelpText>
    <label>Organization Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Foundation_Status__c.field-meta.xml
<CustomField>
    <fullName>Foundation_Status__c</fullName>
    <label>Organization Status</label>
    <type>TextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>This is a four-digit internal number assigned to central/parent organizations holding group exemption letters.</inlineHelpText>
    <label>Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/In_Care_of__c.field-meta.xml
<CustomField>
    <fullName>In_Care_of__c</fullName>
    <inlineHelpText>In Care of Name</inlineHelpText>
    <label>In Care of</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Income_AMT__c.field-meta.xml
<CustomField>
    <fullName>Income_AMT__c</fullName>
    <inlineHelpText>Income Amount is a computer generated amount from the most recent Form 990 series return filed by the organization.
Income Amount is computer generated using PART I, Total Revenue Line 12 and adding &quot;back in&quot; the expense items.</inlineHelpText>
    <label>Income AMT</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Income_CD__c.field-meta.xml
<CustomField>
    <fullName>Income_CD__c</fullName>
    <inlineHelpText>Income Codes relate to the amount of income shown on the most recent Form 990 series return filed by the organization.</inlineHelpText>
    <label>Income CD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Independent__c.field-meta.xml
<CustomField>
    <fullName>Independent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Independent</label>
    <type>Checkbox</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/IRS_Org_Name__c.field-meta.xml
<CustomField>
    <fullName>IRS_Org_Name__c</fullName>
    <label>IRS Organization Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/NTEE_Code__c.field-meta.xml
<CustomField>
    <fullName>NTEE_Code__c</fullName>
    <inlineHelpText>The National Taxonomy of Exempt Entities (NTEE) Code is a four digit code used to classify an exempt organization in
terms of its primary exempt activity.</inlineHelpText>
    <label>NTEE Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <label>Org Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Organaization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organaization_Id__c</fullName>
    <label>Organization Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/PF_Filing_REQ_CD__c.field-meta.xml
<CustomField>
    <fullName>PF_Filing_REQ_CD__c</fullName>
    <inlineHelpText>PF FILING REQUIREMENT CODE
Code Form Numbers
1 990-PF return
0 No 990-PF return</inlineHelpText>
    <label>PF Filing REQ CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Revocation_Date__c.field-meta.xml
<CustomField>
    <fullName>Revocation_Date__c</fullName>
    <label>Revocation Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Ruling_Date__c.field-meta.xml
<CustomField>
    <fullName>Ruling_Date__c</fullName>
    <inlineHelpText>This is the month and year (YYYYMM) on a ruling or determination letter recognizing the organization&apos;s exempt status.</inlineHelpText>
    <label>Ruling Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The EO Status Code defines the type of exemption held by the organization. The following is a list of EO status codes and
their definitions:
 Code Description
01 Unconditional Exemption
02 Conditional Exemption
12 Trust described i</inlineHelpText>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Subsection_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsection_Code__c</fullName>
    <inlineHelpText>Subsection Codes are the codes shown under section 501(c) of the Internal Revenue Code of 1986, which define the category under which an organization may be exempt.</inlineHelpText>
    <label>Subsection Code</label>
    <type>TextArea</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Tax_Year__c.field-meta.xml
<CustomField>
    <fullName>Tax_Year__c</fullName>
    <label>Last filed taxes on:</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Total_Assets__c.field-meta.xml
<CustomField>
    <fullName>Total_Assets__c</fullName>
    <inlineHelpText>Asset Codes relate to the book value amount of assets shown on the most recent Form 990 series return filed by the organization.</inlineHelpText>
    <label>Asset Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <label>Total Expense</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/objects/ShakeCharity__c/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <inlineHelpText>Amount from Form 990, Part 1, Line 12, or Part 1, Line 9, of Form 990EZ</inlineHelpText>
    <label>Revenue Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ShakeCharity/ShakeSharityApp/force-app/main/default/classes/AWSCallout.cls
global class AWSCallout {
     webservice static string callAwsgateway(string EIN) {
        Http http = new Http();
 		string sShakeEIN;
        string sReturn = 'wrongEIN';
        List<ShakeCharity__c> UpdateShakeCharity = new List<ShakeCharity__c>();
		List<ShakeCharity__c> createShakeCharity = new List<ShakeCharity__c>();
		ShakeCharity__c  newShake = new ShakeCharity__c();
        system.debug('EIN====='+EIN );
        string sEIN = EIN.replace('-', ''); 
        string sEndPoint = 'https://agbg6e5ci7.execute-api.us-east-2.amazonaws.com/CharityBeta/charitydata/'+sEIN;
        HttpRequest request = new HttpRequest();

        //Please set the endpoint of API gateway which we are going to create in later section
        request.setEndpoint(sEndPoint);
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');

        // Set the body as a JSON object
        HttpResponse response = http.send(request);
        System.debug('response==='+response.getBody());
        String body;
        string sAccountId;
        JSONParser parser = JSON.createParser(response.getBody());
        system.debug(parser );
        system.debug(parser.nextToken());
        system.debug(parser.getCurrentToken());
		List<Account> oAccount = [SELECT Id FROM Account WHERE EIN__c =:EIN LIMIT 1];
        if(oAccount.size() >0){
        	sAccountId = oAccount[0].Id;     
        }
        List<ShakeCharity__c> lstCharity = [SELECT Id, Name, Bridge_Number__c, Billing_Street__c, Billing_City__c, Billing_State__c, Billing_Pincode__c, Billing_Country__c, Total_Assets__c, Company_Mission__c, Total_Expense__c, Total_Revenue__c, Contact_Email__c, In_Care_of__c, Contact_Phone__c, Contact_Title__c, EIN__c, Form_Type__c, Foundation_Code__c, Independent__c, NTEE_Code__c, County__c,  Organaization_Id__c  FROM ShakeCharity__c WHERE EIN__c=:EIN LIMIT 1];
         if(lstCharity != null && lstCharity.size()>0){
             for(ShakeCharity__c oShakeCharity : lstCharity){
                if(parser.getCurrentToken() == JSONToken.START_OBJECT) {
                    parser.nextValue();
                    system.debug(parser.getCurrentName());
                    parser.nextValue();
                    system.debug(parser.getCurrentName());
                    if(parser.getCurrentName() == 'SORT_NAME') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    } 
                    if (parser.getCurrentName() == 'INCOME_CD') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    } 
                    if (parser.getCurrentName() == 'CITY') {
                        system.debug(parser.getText() );
                        oShakeCharity.Billing_City__c=parser.getText() ;
                        parser.nextValue();
                    }
                    if (parser.getCurrentName() == 'ASSET_AMT') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }
                    if (parser.getCurrentName() == 'AFFILIATION') {
                        
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }
                    if (parser.getCurrentName() == 'EIN') {
                        system.debug(parser.getText() );
                        parser.nextValue();

                    }if (parser.getCurrentName() == 'STREET') {
                        system.debug(parser.getText() );
                        oShakeCharity.Billing_Street__c=parser.getText() ;
                        parser.nextValue();

                    }if (parser.getCurrentName() == 'CLASSIFICATION') {
                        system.debug(parser.getText() );
                        parser.nextValue();

                    } if (parser.getCurrentName() == 'ORGANIZATION') {
                        system.debug(parser.getText() );
                        oShakeCharity.Organaization_Id__c=parser.getText() ;
                        parser.nextValue();

                    } if (parser.getCurrentName() == 'REVENUE_AMT') {
                        system.debug(parser.getText() );
                        oShakeCharity.Total_Revenue__c=parser.getText() ;
                        parser.nextValue();

                    } if (parser.getCurrentName() == 'SUBSECTION') {
                        system.debug(parser.getText() );
                        oShakeCharity.Subsection_Code__c=parser.getText() ;
                        if(parser.getText() == '1'){
                            oShakeCharity.Foundation_Status__c='501(c)(1) ' + + ' Corporations Organized under Act of Congress (including Federal Credit Unions)';
                        }
                        if(parser.getText() == '2'){
                            oShakeCharity.Foundation_Status__c='501(c)(2) ' + + ' Title Holding Corporation for Exempt Organization';
                        }
                        if(parser.getText() == '3'){
                            oShakeCharity.Foundation_Status__c='501(c)(3) ' + + ' Religious, Educational, Charitable, Scientific, Literary, Testing for Public Safety, to Foster National or International Amateur Sports Competition, or Prevention of Cruelty to Children or Animals Organizations';
                        }
                        if(parser.getText() == '4'){
                            oShakeCharity.Foundation_Status__c='501(c)(4) ' + + ' Civic Leagues, Social Welfare Organizations, and Local Associations of Employees';
                        }     
                        if(parser.getText() == '5'){
                            oShakeCharity.Foundation_Status__c='501(c)(5) ' + + ' Labor, Agricultural, and Horticultural Organizations';
                        }
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'ICO') {
                        system.debug(parser.getText() );
                        string sContactPerson = parser.getText();
                        oShakeCharity.In_Care_of__c=sContactPerson.replace('%','') ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'INCOME_AMT') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'ASSET_CD') {
                        system.debug(parser.getText() );
                        oShakeCharity.Total_Assets__c=parser.getText() ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'TAX_PERIOD') {
                        system.debug(parser.getText() );
                        string sTaxYear = parser.getText();
                        string sYear = ((String)sTaxYear).left(4);
                        string sMonth = ((String)sTaxYear).right(2);
                        oShakeCharity.Tax_Year__c=sMonth+'/'+sYear ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'RULING') {
                        system.debug(parser.getText() );
                        string sRuleYear = parser.getText();
                        string sYear = ((String)sRuleYear).left(4);
                        string sMonth = ((String)sRuleYear).right(2);
                        oShakeCharity.Ruling_Date__c=sMonth+'/'+sYear ;
                        parser.nextValue();
                    }

                     if (parser.getCurrentName() == 'ZIP') {
                        system.debug(parser.getText() );
                        oShakeCharity.Billing_Pincode__c=parser.getText() ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'DEDUCTIBILITY') {
                        system.debug(parser.getText() );
                        oShakeCharity.Deductablity_Status_Desacription__c=parser.getText() ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'ACTIVITY') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'FILING_REQ_CD') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'FOUNDATION') {
                        system.debug(parser.getText() );
                        oShakeCharity.Foundation_Code__c=parser.getText() ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'NTEE_CD') {
                        system.debug(parser.getText() );
                        oShakeCharity.NTEE_Code__c=parser.getText() ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'STATUS') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'PF_FILING_REQ_CD') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'ACCT_PD') {
                        system.debug(parser.getText() );
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'STATE') {
                        system.debug(parser.getText() );
                        oShakeCharity.Billing_State__c=parser.getText() ;
                        parser.nextValue();
                    }

                    if (parser.getCurrentName() == 'NAME') {
                        system.debug(parser.getText() );
                        oShakeCharity.IRS_Org_Name__c=parser.getText() ;
                        parser.nextValue();
                    }
                    oShakeCharity.Account__c=sAccountId;
                    UpdateShakeCharity.add(oShakeCharity);
                }   
            } 

        }
		else {
			if(parser.getCurrentToken() == JSONToken.START_OBJECT) {
				parser.nextValue();
				system.debug(parser.getCurrentName());
				parser.nextValue();
				system.debug(parser.getCurrentName());
				if(parser.getCurrentName() == 'SORT_NAME') {
					system.debug(parser.getText() );
					parser.nextValue();
				} 
				if (parser.getCurrentName() == 'INCOME_CD') {
					system.debug(parser.getText() );
                    newShake.Income_CD__c=parser.getText() ;
					parser.nextValue();
				} 
				if (parser.getCurrentName() == 'CITY') {
					system.debug(parser.getText() );
					newShake.Billing_City__c=parser.getText() ;
					parser.nextValue();
				}
				if (parser.getCurrentName() == 'ASSET_AMT') {
					system.debug(parser.getText() );
                    newShake.Asset_AMT__c=parser.getText() ;
					parser.nextValue();
				}
				if (parser.getCurrentName() == 'AFFILIATION') {
					newShake.Affiliation__c=parser.getText() ;
					system.debug(parser.getText() );
					parser.nextValue();
				}
                if (parser.getCurrentName() == 'AUTOMATIC_REVOCATION') {
                    system.debug(parser.getText() );
                    string sAutomaticRev = parser.getText();
                    newShake.Automatic_Revocation__c=sAutomaticRev.replace('\r','') ;
                    parser.nextValue();
                }
				if (parser.getCurrentName() == 'EIN') {
					system.debug(parser.getText() );
                    newShake.EIN__c=parser.getText() ;
                    sShakeEIN=parser.getText() ;
					parser.nextValue();

				}if (parser.getCurrentName() == 'STREET') {
					system.debug(parser.getText() );
					newShake.Billing_Street__c=parser.getText() ;
					parser.nextValue();

				}if (parser.getCurrentName() == 'CLASSIFICATION') {
					system.debug(parser.getText() );
                    newShake.Classification__c=parser.getText() ;
					parser.nextValue();

				} if (parser.getCurrentName() == 'ORGANIZATION') {
					system.debug(parser.getText() );
					newShake.Organaization_Id__c=parser.getText() ;
					parser.nextValue();

				} if (parser.getCurrentName() == 'REVENUE_AMT') {
					system.debug(parser.getText() );
					newShake.Total_Revenue__c=parser.getText() ;
					parser.nextValue();

				} if (parser.getCurrentName() == 'SUBSECTION') {
					system.debug(parser.getText() );
					newShake.Subsection_Code__c=parser.getText() ;
					if(parser.getText() == '1'){
						newShake.Foundation_Status__c='501(c)(1) ' + + ' Corporations Organized under Act of Congress (including Federal Credit Unions)';
					}
					if(parser.getText() == '2'){
						newShake.Foundation_Status__c='501(c)(2) ' + + ' Title Holding Corporation for Exempt Organization';
					}
					if(parser.getText() == '3'){
						newShake.Foundation_Status__c='501(c)(3) ' + + ' Religious, Educational, Charitable, Scientific, Literary, Testing for Public Safety, to Foster National or International Amateur Sports Competition, or Prevention of Cruelty to Children or Animals Organizations';
					}
					if(parser.getText() == '4'){
						newShake.Foundation_Status__c='501(c)(4) ' + + ' Civic Leagues, Social Welfare Organizations, and Local Associations of Employees';
					}     
					if(parser.getText() == '5'){
						newShake.Foundation_Status__c='501(c)(5) ' + + ' Labor, Agricultural, and Horticultural Organizations';
					}
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'ICO') {
					system.debug(parser.getText() );
					string sContactPerson = parser.getText();
					newShake.In_Care_of__c=sContactPerson.replace('%','') ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'INCOME_AMT') {
					system.debug(parser.getText() );
                    newShake.Income_AMT__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'ASSET_CD') {
					system.debug(parser.getText() );
					newShake.Total_Assets__c=parser.getText() ;
                    
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'TAX_PERIOD') {
                    system.debug(parser.getText() );
                    string sTaxYear = parser.getText();
                    if(sTaxYear != null){
                        if(sTaxYear.isNumeric()){
                            string sYear = ((String)sTaxYear).left(4);
                            string sMonth = ((String)sTaxYear).right(2);
                            newShake.Tax_Year__c=sMonth+'/'+sYear ;
                        } 
                        else {
                            newShake.Tax_Year__c=parser.getText();   
                        }
                    }
                    parser.nextValue(); 
                }

				if (parser.getCurrentName() == 'RULING') {
                    system.debug(parser.getText() );
                    string sRuleYear = parser.getText();
                    if(sRuleYear != null){
                        if(sRuleYear.isNumeric()){
                            string sYear = ((String)sRuleYear).left(4);
                            string sMonth = ((String)sRuleYear).right(2);
                            newShake.Ruling_Date__c=sMonth+'/'+sYear ;
                        }
                        else {
                            newShake.Ruling_Date__c=parser.getText();    
                        }
                    }
                    parser.nextValue(); 
                }

				 if (parser.getCurrentName() == 'ZIP') {
					system.debug(parser.getText() );
					newShake.Billing_Pincode__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'DEDUCTIBILITY') {
					system.debug(parser.getText() );
					newShake.Deductablity_Status_Desacription__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'ACTIVITY') {
					system.debug(parser.getText() );
                    newShake.Activity__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'FILING_REQ_CD') {
					system.debug(parser.getText() );
                    newShake.Filing_REQ_CD__c=parser.getText() ;
					parser.nextValue();
				}
                
                if (parser.getCurrentName() == 'OrgNAME') {
					system.debug(parser.getText() );
					newShake.IRS_Org_Name__c=parser.getText() ;
                    newShake.Org_Name__c=parser.getText() ;
					parser.nextValue();
				}
                
                if (parser.getCurrentName() == 'REVOCATION_DATE') {
                    system.debug(parser.getText() );
                    newShake.Revocation_Date__c=parser.getText() ;
                    //oShakeCharity.Foundation__c=parser.getText() ;
                    parser.nextValue();
                }

				if (parser.getCurrentName() == 'FOUNDATION') {
					system.debug(parser.getText() );
					newShake.Foundation__c=parser.getText() ;
					parser.nextValue();
				}
                
				if (parser.getCurrentName() == 'NTEE_CD') {
					system.debug(parser.getText() );
					newShake.NTEE_Code__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'STATUS') {
					system.debug(parser.getText() );
                    newShake.Status__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'PF_FILING_REQ_CD') {
					system.debug(parser.getText() );
                    newShake.PF_Filing_REQ_CD__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'ACCT_PD') {
					system.debug(parser.getText() );
                    newShake.ACCT_PD__c=parser.getText() ;
					parser.nextValue();
				}

				if (parser.getCurrentName() == 'STATE') {
					system.debug(parser.getText() );
					newShake.Billing_State__c=parser.getText() ;
					parser.nextValue();
				}
                if (parser.getCurrentName() == 'GROUP') {
                    system.debug(parser.getText() );
                    newShake.Group__c=parser.getText() ;
                    parser.nextValue();
                }
				newShake.Account__c=sAccountId;
				createShakeCharity.add(newShake);
			} 
		} 
        if(UpdateShakeCharity.size()>0){
            Update UpdateShakeCharity;   
        }
        if(sShakeEIN != null){
         	if(createShakeCharity.size()>0){
                insert createShakeCharity;
                sReturn = 'success';
                return sReturn;
            }  
        }
		else{
			sReturn = 'wrongEIN';
			return sReturn;
        } 
        return sReturn; 
    }
	
}